//! Typed entity IDs.
//!
//! Each ID is `sp_core::spid::SpId<…>` with a stable type prefix (`DATA`
//! "typed IDs"): the string form is `"<prefix>_<uuid>"`, unique within its type
//! and stable for the entity's life. Generated by `sp_core::id_type!`.

use sp_core::id_type;

id_type!(CharacterId, "chr");
id_type!(ChatId, "chat");
id_type!(MessageId, "msg");
id_type!(WorldBlueprintId, "world_blueprint");
id_type!(AdventureId, "adventure_sheet");
id_type!(AdventureMessageId, "adventure_message");
id_type!(GmProposalId, "gm_proposal");
id_type!(DraftId, "draft");
id_type!(MetricId, "metric");

// Builder-session sub-record ids (DATA-14, DATA-15).
id_type!(CharacterBuilderMessageId, "cbm");
id_type!(CharacterBuilderSnapshotId, "cbs");
id_type!(WorldBuilderMessageId, "world_builder_message");
id_type!(WorldBuilderSnapshotId, "world_builder_snapshot");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_carry_their_prefix() {
        // DATA: every entity id has a stable type prefix.
        assert!(CharacterId::new().to_string().starts_with("chr_"));
        assert!(ChatId::new().to_string().starts_with("chat_"));
        assert!(MessageId::new().to_string().starts_with("msg_"));
        assert!(
            WorldBlueprintId::new()
                .to_string()
                .starts_with("world_blueprint_")
        );
        assert!(
            AdventureId::new()
                .to_string()
                .starts_with("adventure_sheet_")
        );
        assert!(MetricId::new().to_string().starts_with("metric_"));
        assert!(DraftId::new().to_string().starts_with("draft_"));
    }

    #[test]
    fn ids_round_trip_through_string() {
        let id = CharacterId::new();
        let parsed: CharacterId = id.to_string().parse().unwrap();
        assert_eq!(id, parsed);
    }
}
